import { previewServiceSession } from "./service-session";
import type { DesktopSnapshot } from "./types";

export const fallbackSnapshot: DesktopSnapshot = {
  service: previewServiceSession,
  distribution: {
    channel: "browser_preview",
    app_version: "0.1.1",
    build_profile: "browser",
    sidecar_policy: "sample_data",
    release_gate: "not_applicable",
    signing: "not_checked",
    notarization: "not_checked",
    message: "Browser preview uses sample data and is not an app bundle.",
  },
  source_count: 1,
  catalog: {
    status: "matches",
    total_matches: 7,
    packages: [
      {
        slug: "fabfilter-pro-q",
        name: "FabFilter Pro-Q 4",
        vendor: "FabFilter",
        version: "4.02",
        product_type: "plugin",
        category: "effects",
        subcategory: "equalizer",
        license: "commercial",
        description: "Transparent equalizer with AU and VST3 formats.",
        is_paid: true,
        is_installable: true,
        installed: true,
        installed_version: "4.02",
        formats: [
          {
            format: "AU",
            install_type: "pkg",
            download_type: "managed",
            has_checksum: false,
          },
          {
            format: "VST3",
            install_type: "pkg",
            download_type: "managed",
            has_checksum: false,
          },
        ],
      },
      {
        slug: "surge-xt",
        name: "Surge XT",
        vendor: "Surge Synth Team",
        version: "1.3.4",
        product_type: "plugin",
        category: "instruments",
        subcategory: "synthesizer",
        license: "GPL-3.0",
        description: "Open-source hybrid synthesizer.",
        is_paid: false,
        is_installable: true,
        installed: true,
        installed_version: "1.3.3",
        formats: [
          {
            format: "AU",
            install_type: "zip",
            download_type: "direct",
            bundle_path: "Surge XT.component",
            has_checksum: true,
          },
          {
            format: "VST3",
            install_type: "zip",
            download_type: "direct",
            bundle_path: "Surge XT.vst3",
            has_checksum: true,
          },
        ],
      },
      {
        slug: "ott",
        name: "OTT",
        vendor: "Xfer Records",
        version: "1.3.7",
        product_type: "plugin",
        category: "effects",
        subcategory: "dynamics",
        license: "freeware",
        description: "Multiband upward/downward compressor.",
        is_paid: false,
        is_installable: true,
        installed: true,
        installed_version: "1.3.6",
        formats: [
          {
            format: "AU",
            install_type: "dmg",
            download_type: "manual",
            has_checksum: false,
          },
          {
            format: "VST3",
            install_type: "dmg",
            download_type: "manual",
            has_checksum: false,
          },
        ],
      },
      {
        slug: "valhalla-supermassive",
        name: "Valhalla Supermassive",
        vendor: "Valhalla DSP",
        version: "4.0.0",
        product_type: "plugin",
        category: "effects",
        subcategory: "reverb",
        license: "freeware",
        description: "Manual download reverb and delay plugin.",
        is_paid: false,
        is_installable: true,
        installed: false,
        formats: [
          {
            format: "AU",
            install_type: "dmg",
            download_type: "manual",
            has_checksum: false,
          },
          {
            format: "VST3",
            install_type: "dmg",
            download_type: "manual",
            has_checksum: false,
          },
        ],
      },
      {
        slug: "direct-pkg-demo",
        name: "Direct PKG Demo",
        vendor: "Example Audio",
        version: "1.0.0",
        product_type: "plugin",
        category: "effects",
        subcategory: "utility",
        license: "freeware",
        description: "Preview package that uses a privileged PKG installer.",
        is_paid: false,
        is_installable: true,
        installed: false,
        formats: [
          {
            format: "VST3",
            install_type: "pkg",
            download_type: "direct",
            bundle_path: "Direct PKG Demo.vst3",
            has_checksum: true,
          },
        ],
      },
      {
        slug: "app-store-synth",
        name: "App Store Synth",
        vendor: "Example Audio",
        version: "1.0.0",
        product_type: "plugin",
        category: "instruments",
        subcategory: "synthesizer",
        license: "commercial",
        description: "Preview package distributed through the Mac App Store.",
        is_paid: true,
        is_installable: true,
        installed: false,
        formats: [
          {
            format: "APP",
            install_type: "mas",
            download_type: "direct",
            bundle_path: "App Store Synth.app",
            has_checksum: false,
          },
        ],
      },
      {
        slug: "demucs",
        name: "Demucs",
        vendor: "apm models",
        version: "4.0.1",
        product_type: "model",
        category: "audio-ai",
        subcategory: "source separation",
        license: "MIT",
        description: "Audio-AI source separation model manifest.",
        is_paid: false,
        is_installable: false,
        installed: false,
        formats: [],
      },
    ],
  },
  installed: [
    {
      slug: "fabfilter-pro-q",
      version: "4.02",
      vendor: "FabFilter",
      formats: [
        {
          format: "AU",
          path: "/Library/Audio/Plug-Ins/Components/FabFilter Pro-Q 4.component",
        },
        {
          format: "VST3",
          path: "/Library/Audio/Plug-Ins/VST3/FabFilter Pro-Q 4.vst3",
        },
      ],
      source: "official",
      pinned: false,
      origin: "external",
    },
    {
      slug: "surge-xt",
      version: "1.3.3",
      vendor: "Surge Synth Team",
      formats: [
        { format: "VST3", path: "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3" },
      ],
      source: "preview",
      pinned: false,
      origin: "apm",
    },
    {
      slug: "ott",
      version: "1.3.6",
      vendor: "Xfer Records",
      formats: [
        { format: "AU", path: "/Library/Audio/Plug-Ins/Components/OTT.component" },
        { format: "VST3", path: "/Library/Audio/Plug-Ins/VST3/OTT.vst3" },
      ],
      source: "preview",
      pinned: false,
      origin: "apm",
    },
  ],
  updates: {
    status: "ready",
    installed_count: 3,
    updates: [
      {
        slug: "ott",
        vendor: "Xfer Records",
        installed_version: "1.3.6",
        available_version: "1.3.7",
        pinned: false,
        origin: "apm",
        action: "installable",
      },
      {
        slug: "surge-xt",
        vendor: "Surge Synth Team",
        installed_version: "1.3.3",
        available_version: "1.3.4",
        pinned: false,
        origin: "apm",
        action: "installable",
      },
    ],
    up_to_date_count: 1,
    pinned_count: 0,
    external_count: 0,
    missing_count: 0,
  },
  models: {
    packages: [
      {
        package: {
          package_id: "demucs@4.0.1",
          name: "demucs",
          version: "4.0.1",
          description: "Music source separation into stems",
          publisher: "apm-core",
          runtime_mode: "native-mlx",
          input: "audio",
          output: "stems",
          parameter_count: 2,
          min_memory_gb: 8,
          commercial_license: true,
        },
        runtime_entry: "demucs_mlx.Separator",
        weights: {
          source: "hf:mlx-community/demucs-mlx-fp16",
          sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
          format: "safetensors",
          cached: false,
        },
        params: [
          {
            name: "stems",
            type: "enum",
            values: ["2", "4", "6"],
            default: "4",
          },
          {
            name: "shifts",
            type: "int",
            min: 1,
            max: 10,
            default: 1,
          },
        ],
      },
    ],
  },
  model_catalog: {
    packages: [
      {
        package: {
          package_id: "demucs@4.0.1",
          name: "demucs",
          version: "4.0.1",
          description: "Music source separation into stems",
          publisher: "apm-core",
          runtime_mode: "native-mlx",
          input: "audio",
          output: "stems",
          parameter_count: 2,
          min_memory_gb: 8,
          commercial_license: true,
        },
        source_name: "official",
        manifest_path: "/Preview Registry/models/demucs/4.0.1.toml",
        manifest_cached: true,
        runtime_entry: "demucs_mlx.Separator",
        weights: {
          source: "hf:mlx-community/demucs-mlx-fp16/model.safetensors",
          sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
          format: "safetensors",
          cached: false,
        },
        params: [
          {
            name: "stems",
            type: "enum",
            values: ["2", "4", "6"],
            default: "4",
          },
          {
            name: "shifts",
            type: "int",
            min: 1,
            max: 10,
            default: 1,
          },
        ],
      },
      {
        package: {
          package_id: "separator-lite@1.0.0",
          name: "separator-lite",
          version: "1.0.0",
          description: "Small preview stem separator for quick audition workflows",
          publisher: "apm-core",
          runtime_mode: "coreml",
          input: "audio",
          output: "stems",
          parameter_count: 1,
          min_memory_gb: 4,
          commercial_license: true,
        },
        source_name: "official",
        manifest_path: "/Preview Registry/models/separator-lite/1.0.0.toml",
        manifest_cached: false,
        runtime_entry: "separator_lite.Model",
        weights: {
          source: "https://example.test/separator-lite.safetensors",
          sha256: "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210",
          format: "safetensors",
          cached: false,
        },
        params: [
          {
            name: "quality",
            type: "enum",
            values: ["draft", "mix"],
            default: "draft",
          },
        ],
      },
    ],
  },
  model_store: {
    root: "~/.apm",
    manifests: "~/.apm/manifests",
    weights: "~/.apm/weights",
    runtimes: "~/.apm/runtimes",
    cache: "~/.apm/cache",
    logs: "~/.apm/logs",
    config: "~/.apm/config.toml",
  },
  diagnostics: {
    summary: {
      ok: 6,
      warnings: 1,
      failures: 0,
    },
    checks: [
      {
        name: "~/Library/Audio/Plug-Ins/Components/",
        status: "ok",
        detail: "readable, writable",
      },
      {
        name: "~/Library/Audio/Plug-Ins/VST3/",
        status: "ok",
        detail: "readable, writable",
      },
      {
        name: "State file",
        status: "ok",
        detail: "~/Library/Application Support/apm/state.toml (3 plugins managed)",
      },
      {
        name: "Managed installs",
        status: "ok",
        detail: "verified 3 managed plugins on disk",
      },
      {
        name: "Privileged helper artifacts",
        status: "ok",
        detail: "no apm privileged helper artifacts installed",
      },
      {
        name: "Model store",
        status: "ok",
        detail: "directories ready: ~/.apm",
      },
      {
        name: "Registry freshness",
        status: "warning",
        detail: "preview registry data",
        hint: "Run a live registry sync from the desktop app before trusting freshness.",
      },
    ],
  },
  recovery: {
    interrupted_count: 1,
    retryable_count: 1,
    candidates: [
      {
        operation_id: "op-preview-retryable",
        kind: "package_update",
        created_at: "2026-06-30T09:40:00Z",
        finished_at: "2026-06-30T09:40:04Z",
        retryable: true,
        reason: "Operation did not finish before the service restarted.",
      },
    ],
  },
  operations: [
    {
      operation_id: "op-preview-retryable",
      kind: "package_update",
      request: {
        kind: "package_update",
        slug: "surge-xt",
        body: { format: "VST3" },
      },
      state: "failed",
      created_at: "2026-06-30T09:40:00Z",
      started_at: "2026-06-30T09:40:00Z",
      finished_at: "2026-06-30T09:40:04Z",
      result: null,
      error: "Operation did not finish before the service restarted.",
      events: [
        {
          event: "install_failed",
          slug: "surge-xt",
          error: "Operation did not finish before the service restarted.",
        },
      ],
    },
    {
      operation_id: "op-preview-install",
      kind: "install_archive",
      request: {
        kind: "install_archive",
        request: {
          slug: "surge-xt",
          version: "1.3.3",
          archive_path: "/Users/example/Downloads/surge-xt.zip",
        },
      },
      state: "succeeded",
      created_at: "2026-06-30T09:52:00Z",
      started_at: "2026-06-30T09:52:00Z",
      finished_at: "2026-06-30T09:52:06Z",
      result: null,
      error: null,
      events: [
        {
          event: "install_started",
          slug: "surge-xt",
          version: "1.3.3",
          format_count: 1,
        },
        {
          event: "install_finished",
          slug: "surge-xt",
          installed_format_count: 1,
        },
      ],
    },
    {
      operation_id: "op-preview-sync",
      kind: "registry_sync",
      request: { kind: "registry_sync" },
      state: "succeeded",
      created_at: "2026-06-30T10:00:00Z",
      started_at: "2026-06-30T10:00:00Z",
      finished_at: "2026-06-30T10:00:02Z",
      result: null,
      error: null,
      events: [
        { event: "registry_sync_started", source_count: 1 },
        {
          event: "registry_sync_finished",
          source_count: 1,
          failed_count: 0,
        },
      ],
    },
    {
      operation_id: "op-preview-remove",
      kind: "package_remove",
      request: {
        kind: "package_remove",
        slug: "legacy-room",
        body: { dry_run: false },
      },
      state: "succeeded",
      created_at: "2026-06-30T10:06:00Z",
      started_at: "2026-06-30T10:06:00Z",
      finished_at: "2026-06-30T10:06:03Z",
      result: null,
      error: null,
      events: [
        {
          event: "remove_started",
          slug: "legacy-room",
          version: "0.9.0",
          format_count: 1,
        },
        {
          event: "remove_finished",
          slug: "legacy-room",
          removed_format_count: 1,
        },
      ],
    },
  ],
};
