id = "arturia-software-center"
name = "Arturia Software Center"
vendor = "arturia"
app_paths = ["/Applications/Arturia/Arturia Software Center.app"]
download_url = "https://www.arturia.com/support/downloads-manuals"
homepage = "https://www.arturia.com/"
