id = "ilok-license-manager"
name = "iLok License Manager"
vendor = "ilok-license"
app_paths = ["/Applications/iLok License Manager.app"]
download_url = "https://www.ilok.com/#!license-manager"
homepage = "https://www.ilok.com/"
