id = "plugin-alliance-installation-manager"
name = "Plugin Alliance Installation Manager"
vendor = "plugin-alliance"
app_paths = ["/Applications/Plugin Alliance/Installation Manager.app"]
download_url = "https://www.plugin-alliance.com/pages/installation-manager"
homepage = "https://www.plugin-alliance.com/"
