id = "softube-central"
name = "Softube Central"
vendor = "softube"
app_paths = ["/Applications/Softube Central.app"]
download_url = "https://www.softube.com/support/how-do-i-install-my-products"
homepage = "https://www.softube.com/"
