id = "spitfire-audio"
name = "Spitfire Audio App"
vendor = "spitfire-audio"
app_paths = ["/Applications/Spitfire Audio.app"]
download_url = "https://www.spitfireaudio.com/"
homepage = "https://www.spitfireaudio.com/"
