id = "toontrack-product-manager"
name = "Toontrack Product Manager"
vendor = "toontrack"
app_paths = ["/Applications/Toontrack Product Manager.app"]
download_url = "https://www.toontrack.com/product-manager/"
homepage = "https://www.toontrack.com/"
